function clientQueryRequestReturn = clientQueryRequest(obj,name,requestTag,queryImageContent)
%clientQueryRequest(obj,name,requestTag,queryImageContent)
%
%     Input:
%       name = (string)
%       requestTag = (string)
%       queryImageContent = (string)
%   
%     Output:
%       clientQueryRequestReturn{:} = (string)

% Build up the argument lists.
values = { ...
   name, ...
   requestTag, ...
   queryImageContent, ...
   };
names = { ...
   'name', ...
   'requestTag', ...
   'queryImageContent', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://services.instancesearch.uit.com', ...
    'clientQueryRequest', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
clientQueryRequestReturn = parseSoapResponse(response);
