function serverConnectReturn = serverConnect(obj,id,name,requestTag)
%serverConnect(obj,id,name,requestTag)
%
%     Input:
%       id = (string)
%       name = (string)
%       requestTag = (string)
%   
%     Output:
%       serverConnectReturn{:} = (string)

% Build up the argument lists.
values = { ...
   id, ...
   name, ...
   requestTag, ...
   };
names = { ...
   'id', ...
   'name', ...
   'requestTag',...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://services.instancesearch.uit.com', ...
    'serverConnect', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
serverConnectReturn = parseSoapResponse(response);
