function testConnectionReturn = testConnection(obj,input)
%testConnection(obj,input)
%
%     Input:
%       input = (string)
%   
%     Output:
%       testConnectionReturn = (string)

% Build up the argument lists.
values = { ...
   input, ...
   };
names = { ...
   'input', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://services.instancesearch.uit.com', ...
    'testConnection', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
testConnectionReturn = parseSoapResponse(response);
